networks:
  bankApp-network:

services:
  consul:
    image: hashicorp/consul:1.21.3
    mem_limit: 700m
    ports:
      - "8500:8500"
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bankApp-network

  configserver:
    image: ximenia851/configserver:latest
    ports:
      - "8071:8071"
    mem_limit: 700m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - bankApp-network

  bankapp:
    image: ximenia851/bankapp:latest
    ports:
      - "8080:8080"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - bankApp-network

  cards:
    image: ximenia851/cards:latest
    ports:
      - "9000:9000"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - bankApp-network

  loans:
    image: ximenia851/loans:latest
    ports:
      - "8090:8090"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - bankApp-network