services:
  bankapp:
    image: ximenia851/bankapp:latest
    ports:
      - "8080:8080"
    mem_limit: 700m

  cards:
    image: ximenia851/cards:latest
    ports:
      - "9000:9000"
    mem_limit: 700m

  loans:
    image: ximenia851/loans:latest
    ports:
      - "8090:8090"
    mem_limit: 700m