services:

  configserver:
    image: ximenia851/configserver:latest
    ports:
      - "8071:8071"
    mem_limit: 700m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  bankapp:
    image: ximenia851/bankapp:latest
    ports:
      - "8080:8080"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy

  cards:
    image: ximenia851/cards:latest
    ports:
      - "9000:9000"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy

  loans:
    image: ximenia851/loans:latest
    ports:
      - "8090:8090"
    mem_limit: 700m
    depends_on:
      configserver:
        condition: service_healthy